server:
  port: 8081

spring:
  config:
    import:
      configserver:http://localhost:8084
  application:
    name: studentProducer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer